name: Daily Weather PDF Download

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Download and extract Chrome & ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.126/linux64/chrome-linux64.zip
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/126.0.6478.126/linux64/chromedriver-linux64.zip
          unzip chrome-linux64.zip
          unzip chromedriver-linux64.zip
          chmod +x chrome-linux64/chrome chromedriver-linux64/chromedriver

      - name: Run the download script
        run: python download_weather_pdf.py

      - name: Move and rename the PDF
        run: |
          TODAY=$(date +%Y-%m-%d)
          mkdir -p reports/$TODAY
          mv downloads/$TODAY/*.pdf reports/$TODAY/weather-$TODAY.pdf

      - name: Commit and push to repo using PAT
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name "Auto Commit Bot"
          git config --global user.email "actions@github.com"
          if git remote | grep origin; then
            git remote set-url origin https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}
          else
            git remote add origin https://x-access-token:${ACTIONS_PAT}@github.com/${{ github.repository }}
          fi
          git fetch origin main
          git checkout main
          git pull origin main
          git add reports/
          git commit -m "Add weather report for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push origin main
